-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

local neogit = require("neogit")

-- Keybindings for Neogit popups
vim.keymap.set("n", "<leader>gs", function()
    neogit.open()
end, { desc = "Open Neogit" })
vim.keymap.set("n", "<leader>gc", function()
    neogit.open({ "commit" })
end, { desc = "Commit Popup" })
vim.keymap.set("n", "<leader>gp", function()
    neogit.open({ "pull" })
end, { desc = "Pull Popup" })
vim.keymap.set("n", "<leader>gP", function()
    neogit.open({ "push" })
end, { desc = "Push Popup" })
vim.keymap.set("n", "<leader>gl", function()
    neogit.open({ "log" })
end, { desc = "Log Popup" })
vim.keymap.set("n", "<leader>gf", function()
    neogit.open({ "fetch" })
end, { desc = "Fetch Popup" })
vim.keymap.set("n", "<leader>gr", function()
    neogit.open({ "rebase" })
end, { desc = "Rebase Popup" })
vim.keymap.set("n", "<leader>gm", function()
    neogit.open({ "merge" })
end, { desc = "Merge Popup" })
vim.keymap.set("n", "<leader>gd", function()
    neogit.open({ "diff" })
end, { desc = "Diff Popup" })
vim.keymap.set("n", "<leader>gst", function()
    neogit.open({ "stash" })
end, { desc = "Stash Popup" })
vim.keymap.set("n", "<leader>gb", function()
    neogit.open({ "branch" })
end, { desc = "Branch Popup" })
vim.keymap.set("n", "<leader>gw", function()
    neogit.open({ "worktree" })
end, { desc = "Worktree Popup" })
