source $HOME/dotfiles/vim/vim_plugins.vim
source $HOME/dotfiles/vim/vim_keybindings.vim

" Appearance {
    set wrap " turn on line wrapping
    set wrapmargin=8 " wrap lines when coming within n characters from side
    set linebreak " set soft wrapping
    set showbreak=… " show ellipsis at breaking
    colorscheme dracula
    syntax on
    filetype plugin indent on

    "make the highlighting of tabs and other non-text less annoying
    highlight SpecialKey ctermfg=236
    highlight NonText ctermfg=236

    set encoding=utf-8
    set guifont=RobotoMono\ Nerd\ Font\ Mono\ 10
    set colorcolumn=80
    set number
    set ttyfast
    set cmdheight=1 "command bar height
    set showmatch "show matching braces
    set hlsearch "highlight all matching search pattern
    let &winheight = &lines * 7 / 10
    let &winwidth = &columns * 7 / 10
    "Airline {
        let g:airline_powerline_fonts=1
        let g:airline_left_sep=''
        let g:airline_right_sep=''
        "let g:airline_theme='base16'
        let g:airline_theme='dracula'
        "let g:airline_theme='dracula'
        let g:airline#extensions#tabline#show_splits = 0
        let g:airline#extensions#whitespace#enabled = 0
        " enable airline tabline
        let g:airline#extensions#tabline#enabled = 1
        " only show tabline if tabs are being used (more than 1 tab open)
        let g:airline#extensions#tabline#tab_min_count = 2
        " do not show open buffers in tabline
        let g:airline#extensions#tabline#show_buffers = 0
        " Show errors in airline from ALE
        let g:airline#extensions#ale#enabled = 1
    " }
" }

" signify {
let g:signify_vcs_list = [ 'git' ]
let g:signify_sign_add = '+'
let g:signify_sign_delete = '_'
let g:signify_sign_delete_first_line = '‾'
let g:signify_sign_change = '~'
" }

" vim-fugitive {
    nmap <silent> <leader>gs :Gstatus<cr>
    nmap <leader>ge :Gedit<cr>
" }

" NERDTree {
    " Toggle NERDTree
    function! ToggleNerdTree()
        if @% != "" && (!exists("g:NERDTree") || (g:NERDTree.ExistsForTab() && !g:NERDTree.IsOpen()))
            :NERDTreeFind
        else
            :NERDTreeToggle
        endif
    endfunction
    " toggle nerd tree
    nmap <silent> <leader>n :call ToggleNerdTree()<cr>
    " find the current file in nerdtree without needing to reload the drawer
    nmap <silent> <leader>f :NERDTreeFind<cr>

    let NERDTreeShowHidden=1
    " let NERDTreeDirArrowExpandable = '▷'
    " let NERDTreeDirArrowCollapsible = '▼'
    let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ 'Ignored'   : '☒',
    \ "Unknown"   : "?"
    \ }
" }

if has('mac')
" ALE {
    let g:ale_sign_error = '✖'
    let g:ale_sign_warning = '⚠'

    "let g:ale_linters = {
    "\    'javascript': ['eslint'],
    "\    'typescript': ['tsserver', 'tslint'],
    "\    'html': []
    "\}
" }
endif

" 1 is the blinky block cursor
" 2 is the default (non-blinky) block cursor
" 3 is blinky underscore
" 4 fixed underscore
" 5 pipe bar (blinking)
" 6 fixed pipe bar
" Change cursor to pipe (|) in insert mode
"au InsertEnter * silent execute \"!echo -en \<esc>[5 q"
"au InsertLeave * silent execute \"!echo -en \<esc>[1 q"
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" Mouse scrolling
nmap <ScrollWheelUp> <C-Y>
nmap <S-ScrollWheelUp> <C-U>
nmap <ScrollWheelDown> <C-E>
nmap <S-ScrollWheelDown> <C-D>

" General scrolling
set scrolloff=5
"set lazyredraw

let python_highlight_all=1
syntax on
"================================

" Trigger configuration. Do not use <tab> if you use
" https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-<Tab>>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" Airline plugin
"let g:airline_theme='dracula'

" Keep more info in memory to speed things up:
set hidden
set history=100

" Smart tabbing and indentation
filetype indent on
set smarttab " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
set tabstop=4 " the visible width of tabs
set shiftwidth=4 " number of spaces to use for indent and unindent
set softtabstop=4 " edit as if the tabs are 4 characters wide
set expandtab
set smartindent
set autoindent
set shiftround " round indent to a multiple of 'shiftwidth'

" code folding settings
set foldmethod=syntax " fold based on indent
set foldlevelstart=99
set foldnestmax=10 " deepest fold is 10 levels
set nofoldenable " don't fold by default
set foldlevel=1

" toggle invisible characters
set list
set listchars=tab:→\ ,trail:⋅,extends:❯,precedes:❮
set showbreak=↪

set t_Co=256 " Explicitly tell vim that the terminal supports 256 colors
if &term =~ '256color'
    " disable background color erase
    set t_ut=
endif

 "enable 24 bit color support if supported
"if (has('mac') && empty($TMUX) && has("termguicolors"))
    "set termguicolors
"endif

" Remove white spaces on save
autocmd BufWritePre * :%s/\s+$//e

" enable . command in visual mode
vnoremap . :normal .<cr>

" Leader key by default is \

" using the variable g:os below you can create OS dependent vim config
"if !exists("g:os")
"    if has("win64") || has("win32") || has("win16")
"        let g:os = "Windows"
"    else
"        let g:os = substitute(system('uname'), '\n', '', '')
"    endif
"endif

set clipboard=unnamed
let g:ycm_global_ycm_extra_conf = '~/dotfiles/vim/plugged/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'

