name: Bug Report 🐞
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "I should have seen..."
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: describe
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you seeing this bug in?
    validations:
      required: true
  - type: dropdown
    id: shells
    attributes:
      label: Which shells are you seeing the problem on?
      multiple: true
      options:
        - sh
        - csh
        - bash
        - zsh
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
