name: Feature Request 💡
description: Suggest a new idea for the project.
title: "[Feature]: "
labels: [enhancement]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to suggest this feature request!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: fals
    - type: textarea
      id: summary
      attributes:
          label: Summary
          description: Brief explanation of the feature.
          placeholder: Tell us what you would like to see! You can also drag-and-drop files here.
      validations:
          required: true
    - type: textarea
      id: example
      attributes:
          label: Basic Example
          description: Brief explanation of the feature.
          placeholder: If the proposal involves a new or changed API, include a basic code example.
      validations:
          required: false
    - type: textarea
      id: motivation
      attributes:
          label: Motivation
          description: Why are we doing this? What use cases does it support? What is the expected outcome?
      validations:
          required: true
    - type: checkboxes
      id: terms
      attributes:
          label: Code of Conduct
          description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
          options:
              - label: I agree to follow this project's Code of Conduct
                required: true
